// Regenerates src/odors/*.ts from assets/. Requires ffmpeg for odors that are re-encoded.
import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const odors = [
  { name: "staccato", source: "fart-dry.mp3", tonnage: [0, 0.6], reencode: true },
  { name: "sustained", source: "fart-chubby.mp3", tonnage: [0.4, 1], reencode: true },
  // Expressive odors: opt-in only, not referenced by presets.
  { name: "soprano", source: "fart-high.mp3", tonnage: [0.3, 0.8], reencode: true },
  { name: "pesante", source: "fart-greasy.mp3", tonnage: [0.5, 1], reencode: true },
  { name: "fortissimo", source: "fart-long-loud.mp3", tonnage: [0.85, 1], reencode: true },
  { name: "sforzando", source: "fart-hard.mp3", tonnage: [0.7, 1], reencode: true },
  { name: "cathedral", source: "fart-loud-reverb.mp3", tonnage: [0.9, 1], reencode: true },
];

/** Peak level targeted by normalization, in dBFS. */
const TARGET_PEAK = -1;
/** Level below which audio counts as silence, in dBFS. */
const SILENCE = "-45dB";
/** Lower threshold for the tail, so that reverberation decays are kept. */
const TAIL_SILENCE = "-60dB";
/** Encoded odors must start sounding within this delay, in seconds. */
const MAX_LEADING_SILENCE = 0.03;
/** Encoded odors must peak at least this loud, in dBFS. */
const MIN_PEAK = -3;

const ffmpeg = (args: string[]): string =>
  execFileSync("ffmpeg", ["-hide_banner", ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });

/** ffmpeg writes analysis results to stderr. */
function analyze(file: string, filter: string): string {
  const result = spawnSync("ffmpeg", ["-hide_banner", "-i", file, "-af", filter, "-f", "null", "-"], {
    encoding: "utf8",
  });
  return result.stderr;
}

function peakOf(file: string): number {
  const match = /max_volume: (-?[\d.]+) dB/.exec(analyze(file, "volumedetect"));
  if (!match) throw new Error(`Could not measure the peak of ${file}`);
  return Number(match[1]);
}

function leadingSilenceOf(file: string): number {
  const output = analyze(file, `silencedetect=n=${SILENCE}:d=0.01`);
  const start = /silence_start: (-?[\d.]+)/.exec(output);
  const end = /silence_end: ([\d.]+)/.exec(output);
  return start && Number(start[1]) <= 0 && end ? Number(end[1]) : 0;
}

// Removes silence at both ends (reversing the stream to trim the tail).
const TRIM = [
  `silenceremove=start_periods=1:start_threshold=${SILENCE}`,
  "areverse",
  `silenceremove=start_periods=1:start_threshold=${TAIL_SILENCE}`,
  "areverse",
].join(",");

const work = mkdtempSync(join(tmpdir(), "puejs-odors-"));
try {
  for (const odor of odors) {
    const input = join(root, "assets", odor.source);
    let file = input;
    if (odor.reencode) {
      const trimmed = join(work, `${odor.name}-trimmed.wav`);
      ffmpeg(["-v", "error", "-i", input, "-af", TRIM, "-ac", "1", "-ar", "22050", "-y", trimmed]);
      const gain = TARGET_PEAK - peakOf(trimmed);
      file = join(work, `${odor.name}.mp3`);
      ffmpeg([
        "-v",
        "error",
        "-i",
        trimmed,
        "-af",
        `volume=${gain.toFixed(2)}dB`,
        "-ac",
        "1",
        "-ar",
        "22050",
        "-b:a",
        "32k",
        "-map_metadata",
        "-1",
        "-y",
        file,
      ]);
    }

    const peak = peakOf(file);
    const leadingSilence = leadingSilenceOf(file);
    if (leadingSilence > MAX_LEADING_SILENCE) {
      throw new Error(`${odor.name} starts with ${leadingSilence.toFixed(3)} s of silence`);
    }
    if (peak < MIN_PEAK) throw new Error(`${odor.name} peaks at ${peak} dB, below ${MIN_PEAK} dB`);

    const bytes = readFileSync(file);
    const source = [
      `// Generated by scripts/encode-odors.ts from assets/${odor.source}. Do not edit.`,
      `import { defineOdor } from "../odor";`,
      ``,
      `export const ${odor.name} = /* @__PURE__ */ defineOdor({`,
      `  name: "${odor.name}",`,
      `  src: "data:audio/mpeg;base64,${bytes.toString("base64")}",`,
      `  tonnage: [${odor.tonnage.join(", ")}],`,
      `});`,
      ``,
    ].join("\n");
    writeFileSync(join(root, "src", "odors", `${odor.name}.ts`), source);
    console.log(`${odor.name}: ${bytes.length} bytes, peak ${peak} dB, leading silence ${leadingSilence.toFixed(3)} s`);
  }
} finally {
  rmSync(work, { recursive: true, force: true });
}
