// Regenerates src/odors/*.ts from assets/. Requires ffmpeg for odors that are re-encoded.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const odors = [
  // Re-encoded to mono 22.05 kHz to match fart-chubby.mp3 and shrink the inlined payload.
  { name: "staccato", source: "fart-dry.mp3", tonnage: [0, 0.6], reencode: true },
  { name: "sustained", source: "fart-chubby.mp3", tonnage: [0.4, 1], reencode: false },
];

const work = mkdtempSync(join(tmpdir(), "puejs-odors-"));
try {
  for (const odor of odors) {
    const input = join(root, "assets", odor.source);
    let file = input;
    if (odor.reencode) {
      file = join(work, `${odor.name}.mp3`);
      execFileSync("ffmpeg", [
        "-v",
        "error",
        "-i",
        input,
        "-ac",
        "1",
        "-ar",
        "22050",
        "-b:a",
        "32k",
        "-map_metadata",
        "-1",
        "-y",
        file,
      ]);
    }
    const bytes = readFileSync(file);
    const source = [
      `// Generated by scripts/encode-odors.ts from assets/${odor.source}. Do not edit.`,
      `import { defineOdor } from "../odor";`,
      ``,
      `export const ${odor.name} = /* @__PURE__ */ defineOdor({`,
      `  name: "${odor.name}",`,
      `  src: "data:audio/mpeg;base64,${bytes.toString("base64")}",`,
      `  tonnage: [${odor.tonnage.join(", ")}],`,
      `});`,
      ``,
    ].join("\n");
    writeFileSync(join(root, "src", "odors", `${odor.name}.ts`), source);
    console.log(`${odor.name}: ${bytes.length} bytes`);
  }
} finally {
  rmSync(work, { recursive: true, force: true });
}
